### ISSUE TITLE
Add to js-ipfs bundles

### ISSUE THREAD

**Issue by jacobheun** [libp2p/pull-mplex#7]
This issue is for tracking the release of `pull-mplex` into js-ipfs, as a replacement for `libp2p-mplex`.

- [x] Initial release of pull-mplex
- [x] Add pull-mplex to js-libp2p-switch test suite https://github.com/libp2p/js-libp2p-switch/pull/305
- [x] Add pull-mplex to js-libp2p test suite https://github.com/libp2p/js-libp2p/pull/325
- [x] Replace libp2p-mplex with pull-mplex in js-ipfs bundles https://github.com/ipfs/js-ipfs/pull/1884
  - [x] Run js-ipfs test suites
  - [x] Run ipfs/interop tests with pull-mplex branch for js-ipfs https://github.com/ipfs/interop/pull/67

**Comment by daviddias** [comment]
@jacobheun it would be great if pull-mplex (or future async/generators-mplex) was just the internals libp2p-mplex. There should be no need to have multiple concurrent implementations, there should just be, however, tons of tests to ensure the soundness of each of these migrations as Stream Muxing has been historically a PITA.

**Comment by daviddias** [comment]
For example, make sure to run the _mega stress test_ https://github.com/libp2p/interface-stream-muxer/blob/master/src/mega-stress-test.js#L7 and compare both implementations.

**Comment by jacobheun** [comment]
> it would be great if pull-mplex (or future async/generators-mplex) was just the internals libp2p-mplex.

I agree. It was a bit easier to test the two side by side being separate but there are other ways to do that, but the new implementations should just be the libp2p-mplex internals. I think the stream muxers need more test in general, it's difficult to debug issues when they arise, so avoiding as many of those as possible up front with more in depth testing is ideal.

Some mega stress test comparison runs:

|libp2p-mplex|pull-mplex| % Faster |
|---:|---:|---:|
|1475641ms | 1022068ms | 30.74% |
|1247929ms | 1083919ms | 13.14% |
|1563942ms | 1078838ms | 31.02% |

**Comment by daviddias** [comment]
@jacobheun those are great results! 

> new implementations should just be the libp2p-mplex internals.

Can this be done before importing it into js-ipfs bundle?

**Comment by jacobheun** [comment]
> Can this be done before importing it into js-ipfs bundle?

It's already in the bundle and it's slated to get released with js-ipfs 0.36, which I believe is going out today.

**Comment by daviddias** [comment]
For those following, there is a new mplex version using those HAWT async iterators at https://github.com/libp2p/js-libp2p-mplex/pull/94
